### ISSUE TITLE
Sketchplugin won't open or install in Sketch

### ISSUE THREAD

**Issue by mhaes** [novemberfiveco/symbol-spacer-sketch-plugin#1]
Hi there, I would love to use this plugin. I followed your instructions but when I double click the novemberfive-symbol-spacer.sketchplugin it opens Sketch, but doesnt open an install pop-up.

What can I do?

Best, Maaike

**Comment by Yatsun** [comment]
Same problem for me --"

**Comment by GeertWille** [comment]
Make sure you download the [release](https://github.com/novemberfiveco/symbol-spacer-sketch-plugin/releases) not the source code. If you do the latest follow the install instructions as stated in the [readme](https://github.com/novemberfiveco/symbol-spacer-sketch-plugin/blob/master/README.md).
