### ISSUE TITLE
Renaming symbols impossible

### ISSUE THREAD

**Issue by ErikFontanel** [novemberfiveco/symbol-spacer-sketch-plugin#3]
Every symbol I rename gets changed back to the master's name. Very inconvenient if you have symbols organised in folders and want to rename them for short field names in the overrides panel. 

I haven't got the time to fork this repo yet but I think this has to do with the if statement here:
https://github.com/novemberfiveco/symbol-spacer-sketch-plugin/blob/master/src/Resizer.js#L26

Keep up the good work :)

**Comment by GeertWille** [comment]
Thanks for the feedback. ;) Normally you should be able to disable the renaming behavior if you go to the plugin settings screen. Hopefully that solves your problem. :)

**Comment by ErikFontanel** [comment]
Yeah, disabling the renaming works for all symbols, but unfortunately it also stops the 'spacer' symbols from being renamed. I want best of both worlds ;).

**Comment by chsWeb** [comment]
Also having this problem.

**Comment by yeta1** [comment]
Yup same issue, Love this plugin but I thought it was supposed to only rename the Spacer Symbol.

**Comment by ChadNicholas** [comment]
Changing the preferences option didn't stop other symbols from getting their names changed back to default for me. I had to kill the plugin. :(

**Comment by zaneriley** [comment]
Hi gang, 

If you need this change right now, you can edit your plugin to only change the symbols you specific in `preferences.` Here's a pull request with the specific code change:

https://github.com/novemberfiveco/symbol-spacer-sketch-plugin/pull/7

**Comment by GeertWille** [comment]
thanks @zaneriley!
