### ISSUE TITLE
Doesn't show in Plugins menu

### ISSUE THREAD

**Issue by jimhare** [novemberfiveco/symbol-spacer-sketch-plugin#4]
Regards from sunny London!
Thanks for the plugin – great concept – but doesn't seem to install in Sketch v45.2.
I've tried double-clicking and dragging the whole release folder into the Plugins folder. 
Also tried with the latest Github master. 
Runner detects the "install", but Sketch doesn't.

**Comment by diancat** [comment]
I have the exactly same problem.

**Comment by frgod** [comment]
I have the same issue too :-(

**Comment by jimhare** [comment]
Hi NovemberFive, is this supposed to work now? Like @frgod mentioned it's still unusable, yet you updated the plugin 8 days ago. Thanks for the plugin!

**Comment by frgod** [comment]
After readed closed issues, i have found the solution. Download release and not github files. It works

**Comment by arpir** [comment]
very nice ！Download release and not github files. It works！😘  frgod

**Comment by jimhare** [comment]
Solution: download and use the actual Release rather than grabbing the plugin file directly. Thanks for the plugin!
