### ISSUE TITLE
Not working on sketch 46.2

### ISSUE THREAD

**Issue by ghost** [novemberfiveco/symbol-spacer-sketch-plugin#5]
Hi,

I try your nice plugin, but I don't see it in plugin when I lunch your sketch file.
Any idea.

Regards
Burnside

**Comment by GeertWille** [comment]
Hey,

Can you double check that you followed the proper installation instructions?

Thanks!

**Comment by ghost** [comment]
Hi,

It work's nice, but I must not do the update with : Sketch Plugin Manager, If I do it it break your plugin.

I just play with it now ;)

**Comment by GeertWille** [comment]
@Burnside666 yes that's right. I'll look into it later how we can solve this issue.
