### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by atillacode** [novemberfiveco/symbol-spacer-sketch-plugin#6]
Hi,

i tried the plugin to get running, but for some reason it does not update to the original size of the selected symbol automatically?
I'm using the latest Sketch v46.2.

Cheers,
Atilla

**Comment by chadbergman** [comment]
I am also unable to install this plugin with v46.2 or beta 47 (45359).

**Comment by argirisb** [comment]
Hello.

I'm getting a similar behaviour - I'm trying a fresh install (new Sketch user) but the plugin doesn't get installed.

Thanks,
Argiris

**Comment by chadbergman** [comment]
I was able to get this to install after a little debugging. It looks like it's related to a bug in /node_modules/sketch-module-web-view/lib/index.js. There is an extra closing parenthesis on line 97 which breaks it from building.

Once I removed that I was able to build the plugin and install it where it is working with 46.2 and beta 47.

**Comment by argirisb** [comment]
@chadbergman Great news! Would you please attach the ZIP of the new build here?
